apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-k8s-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sadanki/java-k8s-project
    targetRevision: HEAD
    path: java-k8s-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: java-k8s-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
