apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-k8s-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/java-k8s-helm-chart
    targetRevision: main
    path: java-k8s-chart
    helm:
      releaseName: java-app
  destination:
    server: https://kubernetes.default.svc
    namespace: java-k8s-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
