apiVersion: v1
kind: Service
metadata:
  name: java-k8s-service
  namespace: java-k8s-ns
spec:
  type: NodePort
  selector:
    app: java-k8s-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
